!function(e,n){"object"==typeof exports&&"undefined"!=typeof module?n(exports,require("react"),require("classnames"),require("react-router-dom")):"function"==typeof define&&define.amd?define(["exports","react","classnames","react-router-dom"],n):n((e="undefined"!=typeof globalThis?globalThis:e||self)["mj-tools"]={},e.react,e.classnames,e["react-router-dom"])}(this,(function(e,n,r,t){"use strict";function o(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var a=o(n),i=o(r),c=function(){return c=Object.assign||function(e){for(var n,r=1,t=arguments.length;r<t;r++)for(var o in n=arguments[r])Object.prototype.hasOwnProperty.call(n,o)&&(e[o]=n[o]);return e},c.apply(this,arguments)};
/**
     * @description 全局的一些配置
     * @author minjie
     * @Date 2022-03-08 17:57
     * @LastEditTime 2022-03-10 18:19
     * @LastEditors minjie
     * @copyright Copyright © 2021 Shanghai Yejia Digital Technology Co., Ltd. All rights reserved.
     */
var u={},l=function(e,n,r){if(void 0===n&&(n="contain"),void 0===r&&(r=[]),"development"===process.env.NODE_ENV)return!0;if("string"==typeof e)return r&&r.includes(e);if(r){if("contain"===n)return(t=r.findIndex((function(n){return e.includes(n)})))>=0;for(var t=0;t<e.length;t++){var o=e[t];if(!r.includes(o))return!1}return!0}return!1},s={success:"#6ABF47",info:"#1281FF",warning:"#FE7A38",error:"#F5222D",gay:"#CCCCCC",default:"#333333"};e.baseAuthenticated=l,e.default=function(e){var n=e.value,r=e.children,o=e.to,d=e.cursor,f=e.powerCode,p=e.notValueText,v=void 0===p?"---":p,y=e.style,b=void 0===y?{}:y,m=e.powerCodeData,g=e.replace,C=e.disabled,h=void 0!==C&&C,O=e.isbackground,j=void 0!==O&&O,w=e.type,k=void 0===w?"info":w,x=e.onChange,E=e.onClick,D=function(e,n){var r={};for(var t in e)Object.prototype.hasOwnProperty.call(e,t)&&n.indexOf(t)<0&&(r[t]=e[t]);if(null!=e&&"function"==typeof Object.getOwnPropertySymbols){var o=0;for(t=Object.getOwnPropertySymbols(e);o<t.length;o++)n.indexOf(t[o])<0&&Object.prototype.propertyIsEnumerable.call(e,t[o])&&(r[t[o]]=e[t[o]])}return r}(e,["value","children","to","cursor","powerCode","notValueText","style","powerCodeData","replace","disabled","isbackground","type","onChange","onClick"]),F=function(e){!h&&E&&E(e)},P=function(){var e={};e[j?"backgroundColor":"color"]=["warning","info","success","error","gay","default"].includes(k)?s[k]:k,d&&(e.cursor=d);var u=x?n||v:r;return a.default.createElement("span",c({className:i.default("sjcomon-span",{"sjcomon-span-diable":h,"sjcommon-span-backaground":j}),style:c(c({},e),b),onClick:F},D),o&&!h&&a.default.createElement(t.Link,{replace:g,to:o},u),!(o&&!h)&&u)};return f?function(e,n){return void 0===n&&(n="contain"),l(e,n,u.power)}(f)?P():null:m?function(e,n){return void 0===n&&(n="contain"),l(e,n,u.powerData)}(m)?P():null:P()},Object.defineProperty(e,"__esModule",{value:!0})}));
//# sourceMappingURL=index.js.map
